### ISSUE TITLE
Specs needed for scraping process

### ISSUE THREAD

**Issue by joshrieken** [tiwatson/wanderinglabs-availability#2]
It's beastly!

**Comment by tiwatson** [comment]
I just added to the readme a bit. Help understand how the scraping actually works: 

Scraping goes down like so:
- Get request made to campground page to set session (LocationConnection)
- Post request made to campground page to set filters (LocationFilter)
- Multiple get requests made for next availability (LocationScraper)

**Comment by tiwatson** [comment]
New version has some scraper tests.. 

https://github.com/tiwatson/wandering-labs-availability-2/tree/master/scraper/test/reserve-america
