### ISSUE TITLE
Is the script active or abandoned?

### ISSUE THREAD

**Issue by r3b3lspy** [tiwatson/wanderinglabs-availability#8]
Thanks for coding this, it looks like an amazing script but I posted a couple of queries o your website at http://reserve.wanderinglabs.com and I'm not getting any e-mails, I just came back today from Bahia Honda SP and there are 9 sites available showing on Reserve America but testing your script is not sending any sms or e-mails, I'll appreciate your answer as I would love to work with a script like yours, in case you are not working with the script anymore please let me know if you'll be interested in developing the script for a fee.

Thanks a lot for your time.

**Comment by tiwatson** [comment]
It looks like Reserve America has denied access to the server running the scraper. I hope to rebuilt it a little more robust and kinder to their servers so hopefully it doesn't get blocked again. I'm not sure on the timeline just yet. Feel free to reach out to me at tiwatson@gmail.com if you have any suggestions or questions.

**Comment by tiwatson** [comment]
@r3b3lspy 
Finally got this back up and running. Did a complete rewrite. Better and more stable then ever. 

https://github.com/tiwatson/wandering-labs-availability-2
http://reserve.wanderingslabs.com

**Comment by r3b3lspy** [comment]
That is fantastic thank you for working on the script, are you going to have it public in your server or are you building something bigger for reservation availability?

**Comment by tiwatson** [comment]
I will be adding a few more features onto it. As well as some bug fixes. Other than that, no big plans.
